
/* Drop Tables */

DROP TABLE FILMING_ITEM;
DROP TABLE FILMING_PHOTO;
DROP TABLE FILMING_PLACE;
DROP TABLE PLACE_TAG_ID;




/* Create Tables */

CREATE TABLE FILMING_PHOTO
(
	FILMING_NO integer NOT NULL,
	PHOTO_NO integer NOT NULL UNIQUE,
	PRIMARY KEY (FILMING_NO)
);


CREATE TABLE PLACE_TAG_ID
(
	PLACE_TAG_ID integer NOT NULL,
	PLACE_TAG_NAME text,
	PRIMARY KEY (PLACE_TAG_ID)
);


CREATE TABLE FILMING_PLACE
(
	FILMING_PLACE_ID integer NOT NULL,
	PLACE_TAG_ID integer NOT NULL,
	PLACE_NAME text,
	PRIMARY KEY (FILMING_PLACE_ID),
	FOREIGN KEY (PLACE_TAG_ID)
	REFERENCES PLACE_TAG_ID (PLACE_TAG_ID)
);


CREATE TABLE FILMING_ITEM
(
	ITEM_NO integer NOT NULL UNIQUE PRIMARY KEY AUTOINCREMENT,
	FILMING_NO integer NOT NULL,
	FILMING_DATE text NOT NULL,
	FILMING_PLACE_ID integer,
	FILMING_MEMO text,
	PRIMARY KEY (ITEM_NO),
	FOREIGN KEY (FILMING_NO)
	REFERENCES FILMING_PHOTO (FILMING_NO),
	FOREIGN KEY (FILMING_PLACE_ID)
	REFERENCES FILMING_PLACE (FILMING_PLACE_ID)
);



