package com.example.sakuban;

import com.example.sakuban.SKBNActivity.*;

import java.util.ArrayList;
import java.util.Iterator;
import db.DbAdapter;
import db.WLOG_DEF;
import android.net.Uri;
import android.os.Bundle;
import android.app.Activity;
import android.content.ContentValues;
import android.content.Intent;
import android.database.Cursor;
import android.util.Log;
import android.view.Menu;
import android.view.MenuItem;
import android.view.View;
import android.view.View.OnClickListener;
import android.widget.ArrayAdapter;
import android.widget.Button;
import android.widget.CheckedTextView;
import android.widget.DatePicker;
import android.widget.EditText;
import android.widget.Spinner;
import android.widget.TextView;
import android.widget.TimePicker;
import junit.framework.TestCase;

public class SKBNActivityTest extends TestCase {

	public void test_type() throws Exception {
		// TODO auto-generated by JUnit Helper.
		assertNotNull(SKBNActivity.class);
	}

	public void test_instantiation() throws Exception {
		// TODO auto-generated by JUnit Helper.
		SKBNActivity target = new SKBNActivity();
		assertNotNull(target);
	}

	public void test_onCreate_A$Bundle() throws Exception {
		// TODO auto-generated by JUnit Helper.
		SKBNActivity target = new SKBNActivity();
		Bundle savedInstanceState = null;
		target.onCreate(savedInstanceState);
	}

	public void test_onCreateOptionsMenu_A$Menu() throws Exception {
		// TODO auto-generated by JUnit Helper.
		SKBNActivity target = new SKBNActivity();
		Menu menu = null;
		boolean actual = target.onCreateOptionsMenu(menu);
		boolean expected = false;
		assertEquals(expected, actual);
	}

	public void test_registSTART_A$View() throws Exception {
		// TODO auto-generated by JUnit Helper.
		SKBNActivity target = new SKBNActivity();
		View v = null;
		target.registSTART(v);
	}

	public void test_registEND_A$View() throws Exception {
		// TODO auto-generated by JUnit Helper.
		SKBNActivity target = new SKBNActivity();
		View v = null;
		target.registEND(v);
	}

	public void test_moveToList_A$View() throws Exception {
		// TODO auto-generated by JUnit Helper.
		SKBNActivity target = new SKBNActivity();
		View v = null;
		target.moveToList(v);
	}

	public void test_moveToSelect_A$View() throws Exception {
		// TODO auto-generated by JUnit Helper.
		SKBNActivity target = new SKBNActivity();
		View v = null;
		target.moveToSelect(v);
	}

}
